### PR TITLE
New media_server package.

### PR DESCRIPTION
**Pull request by cburbridge**
This package provides a means of storing images, music and videos inside mongodb in a way that can be integrated with user interfaces. A web interface is provided for uploading files and managing "file sets" (basicaly photo albums or playlists).

### CODE REVIEW

**Comment by marc-hanheide** [comment]
All I'm wondering is if this name is too generic. When we release this will be turned into a `ros-indigo-media-server` package. I have no really good suggestion, just wanted to see if you do?

**Comment by hawesie** [comment]
Can we rename it mongodb_media_server?  I think we should start making our package names more specific when we create them to make it easier to release to the main ROS community later.

**Comment by marc-hanheide** [comment]
That's what I meant, yes.

**Comment by hawesie** [comment]
Hah! I sent my comment by email hours ago and it only just showed up. We really are on the same page today.

**Comment by hawesie** [comment]
@cburbridge I'd like to start using this for the UAM demo, so please could you make the name change?

**Comment by cburbridge** [comment]
`mongodb_media_server` is fine. Should it then live here, or in mongodb_store? Although I want to initially use it for web GUIs it could be a generic file store, so maybe it should be `mongodb_file_store` akin to the `message_store`?

**Comment by hawesie** [comment]
Let’s keep it here for now. If it becomes more generally used then we can reconsider it.

**Pull request merged**
