### PR TITLE
[mary_tts] initial version using the new pygame_managed_player

### PR DESCRIPTION
**Pull request by marc-hanheide**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I cannot test this right now (my mac doesn't run it). If anyone has a chance, that is welcomed, otherwise, I'll do when I have access to a computer.

**Comment by marc-hanheide** [comment]
I fixed a few bugs and cleaned the code

**Comment by marc-hanheide** [comment]
Oh, and I tested it on my Mac (of course it works if done correctly).

**Comment by cdondrup** [comment]
I'll test it tomorrow.

**Comment by marc-hanheide** [comment]
more than enough. Cheers!

**Comment by marc-hanheide** [comment]
did you have a chance to look at it?

**Comment by cdondrup** [comment]
Works perfectly. I also tried to generate a quite long sentence to check if mary still returns too early. pygame seems to fix the issue that the action is marked as succeeded before the sentence has been played. The only thing preventing it from working is this:

```
[WARN] [WallTime: 1424193851.418306] mary speach action failed; maybe took too long (more than 10 seconds), maybe pulse is broke.
```

Which just forces the action to terminate even if everything is working fine. Feel free to merge if you don't want to have a look at that issue now. Otherwise, it works fine.

**Comment by marc-hanheide** [comment]
This is by purpose, to prevent it hanging when the audio hangs. That's probably not an issue with pygame anymore but was with pulse. Hence, I'd say we merge this know, but maybe can get rid of that "hack" later on. It doesn't harm, though.

**Pull request merged**
