### PR TITLE
Modal dlg

### PR DESCRIPTION
**Pull request by marc-hanheide**
This creates a new actionlib server that allows to display modal dialogs on top of whatever is currently displayed. This is in response to https://github.com/strands-project/aaf_deployment/issues/391#issuecomment-269458816 (hence, this should be used by [`monitored_navigation`](https://github.com/strands-project/strands_navigation/tree/indigo-devel/monitored_navigation) to interact with the user.

New functionality is documented in https://github.com/strands-project/strands_ui/blob/modal_dlg/strands_webserver/README.md#modal-dialog

Best to be tested by @bfalacerda first.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
This is now also deployed on Henry via updated #105. It's working nicely. I'm 👍  for merging this.

**Comment by bfalacerda** [comment]
@marc-hanheide I have no way to implement a timeout in this version, can you add one to the goal definition?

**Comment by marc-hanheide** [comment]
Ok, no problem.

**Comment by marc-hanheide** [comment]
timeout implemented in bf8d5ba3c59427c7e97d2465ffc6d1cb8c950f15, @bfalacerda

**Comment by bfalacerda** [comment]
@marc-hanheide  sorry but i didn't look properly at my code before asking for the timeout. Using it in the action goal would require a lot more changes to the screen help than I thought... The easiest way would be to have a service that removes the dialog, then I could just replace [this line](https://github.com/strands-project/strands_recovery_behaviours/blob/hydro-devel/strands_human_help/src/strands_human_help/help_screen.py#L79) by a call to that service. Could you implement such a service?

**Comment by marc-hanheide** [comment]
@bfalacerda that would really be ugly... We don't you just create an action client in https://github.com/strands-project/strands_recovery_behaviours/blob/hydro-devel/strands_human_help/src/strands_human_help/help_screen.py? And then in [`generate_help_content`](https://github.com/strands-project/strands_recovery_behaviours/blob/hydro-devel/strands_human_help/src/strands_human_help/help_screen.py#L88-L94) you send the goal and in [`help_finished`](https://github.com/strands-project/strands_recovery_behaviours/blob/hydro-devel/strands_human_help/src/strands_human_help/help_screen.py#L78-L79) you dismiss it? 
I mean, how does it work in general for you? You would also react to the button being pressed, right? It seems to me that it might be easier instead create a new `help_screen` type of class and use that? Like `help_dialog` which just uses the action client. I don't understand the current logic really. How is `help_finished` currently even triggered? With an action client this would be easily done, just register callback for the `success`, and `preempts` right?

**Comment by bfalacerda** [comment]
The timeouts are triggered at the smach state level. the state then calls a service that triggers the corresponding behaviour from the different ui's (screen, speech).

But yeah, I just need to cancel the goal! No timeout needed. Was still thinking of this as a service, my bad.. Cheers

**Review by bfalacerda — APPROVED** [review]
I approve of this PR

**Pull request merged**
