### PR TITLE
added install targets to fix #48

### LINKED ISSUE #48: [strands_webserver]not generating help pages anymore
i-m getting this when I launch the released webserver:

```
Request for:  /
localhost - - [11/Nov/2014 15:43:41] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 38339)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 638, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/ros/hydro/lib/strands_webserver/strands_webserver", line 62, in do_GET
    data = render.main(name)
  File "/usr/lib/pymodules/python2.7/web/template.py", line 1021, in __getattr__
    t = self._template(name)
  File "/usr/lib/pymodules/python2.7/web/template.py", line 1018, in _template
    return self._load_template(name)
  File "/usr/lib/pymodules/python2.7/web/template.py", line 1005, in _load_template
    raise AttributeError, "No template named " + name
AttributeError: No template named main
----------------------------------------
Request for:  /favicon.ico
localhost - - [11/Nov/2014 15:43:41] code 404, message File not found
localhost - - [11/Nov/2014 15:43:41] "GET /favicon.ico HTTP/1.1" 404 -
```

Then, when I try to generate the help page for monitored nav, i get this:

```
[ERROR] [WallTime: 1415720299.708114] Error processing request: No template named buttons_multi_service
['Traceback (most recent call last):\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_reque
st\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/strands/bruno_ws/src/strands_navigation/m
onitored_navigation/src/monitored_navigation/help_manager.py", line 50, in forward_callback\n    helper.process_help_request(req)\n', '  File "/home/strands/bruno_ws/src/strands_navigation/monitored_navigation/src/monitored_navigation/ui_helper.py", line 15, in process_help_request\n    self.ask_he$p(req.failed_component, req.interaction_service,req.n_fails)\n', '  File "/home/strands/bruno_ws/src/strands_recovery_behaviours/strands_human_help/s$c/strands_human_help/help_screen.py", line 45, in ask_help\n    self.generate_help_content(self.help_label, self.nav_help_html,  interaction_service)$n', '  File "/home/strands/bruno_ws/src/strands_recovery_behaviours/strands_human_help/src/strands_human_help/help_screen.py", line 64, in generate_h$lp_content\n    content = strands_webserver.page_utils.generate_alert_button_page(html, buttons, self.service_prefix)\n', '  File "/opt/ros/hydro/lib$python2.7/dist-packages/strands_webserver/page_utils.py", line 20, in generate_alert_button_page\n    return generate_button_page(\'<div class="notic$">\' + notice + \'</div>\', buttons, service_prefix)\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/strands_webserver/page_utils.py", line 1$, in generate_button_page\n    return str(render.buttons_multi_service(notice, buttons, service_prefix))\n', '  File "/usr/lib/pymodules/python2.7/we$/template.py", line 1021, in __getattr__\n    t = self._template(name)\n', '  File "/usr/lib/pymodules/python2.7/web/template.py", line 1018, in _tem$late\n    return self._load_template(name)\n', '  File "/usr/lib/pymodules/python2.7/web/template.py", line 1005, in _load_template\n    raise Attrib$teError, "No template named " + name\n', 'AttributeError: No template named buttons_multi_service\n']
```

### PR DESCRIPTION
**Pull request by marc-hanheide**
this pull requests closes #48

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
I think you need to either also do this for `strands_ui` or move `strands_webtools/main.html`, because:

```
strands@karl:~$ dpkg -L ros-hydro-strands-webtools | grep index.html
/opt/ros/hydro/share/strands_webtools/keyboardteleopjs/doc/index.html
/opt/ros/hydro/share/strands_webtools/mjpegcanvasjs/doc/index.html
/opt/ros/hydro/share/strands_webtools/nav2djs/doc/index.html
/opt/ros/hydro/share/strands_webtools/ros2djs/doc/index.html
/opt/ros/hydro/share/strands_webtools/ros3djs/doc/index.html
/opt/ros/hydro/share/strands_webtools/roslibjs/doc/index.html
strands@karl:~$ dpkg -L ros-hydro-strands-webtools | grep main.html
strands@karl:~$ find ALL_THE_FUCKING_STRANDS/ -name main.html
ALL_THE_FUCKING_STRANDS/strands_ui/strands_webserver/data/main.html
ALL_THE_FUCKING_STRANDS/strands_webtools/main.html
strands@karl:~$ dpkg -L ros-hydro-strands-ui | grep main.html
strands@karl:~$
```

**Comment by marc-hanheide** [comment]
Are you sure you have the latest version and you are looking at the right place? It is in `strands_webserver`, I don't think you should need the strands_webtools one. Right @hawesie ?

```
> dpkg -L ros-hydro-strands-webserver  | grep main.html
/opt/ros/hydro/share/strands_webserver/data/main.html
```

**Comment by lucasb-eyer** [comment]
argh, webtools != webserver, you are right.

**Comment by marc-hanheide** [comment]
as @BFALacerda stated: 

> @lucasb-eyer what's missing is a node that sets the main page for the webserver. I dont know which one will be doing it in the marathon system

So I consider this invalid. Reopen if you find a real bug ;-)

**Pull request merged**
