### PR TITLE
Mary tts

### PR DESCRIPTION
**Pull request by marc-hanheide**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
This is importing mary_tts

**Comment by marc-hanheide** [comment]
sorry, that was too early

**Comment by marc-hanheide** [comment]
This should now be mergeable, once it works, please also merge https://github.com/strands-project/strands_hri/pull/69

**Comment by cdondrup** [comment]
What about all the other PRs mentioned in this one? Since mary has been renamed they need to be merged or the affected components won't work anymore.

**Comment by marc-hanheide** [comment]
done... sorry, stopped half way through

**Comment by cdondrup** [comment]
Thank you!

**Pull request merged**
