### PR TITLE
Pygame player

### PR DESCRIPTION
**Pull request by marc-hanheide**
This implements a pygame based player class that can (and should) be instantiated in any sound playing nodes (e.g. Mary, Music player of the walking group, sample playing for navigation feedback, etc.)
It uses some negotiation between different instances of this class using a shared ROS topic and priorities to control the volume. E.g. speech output should be set to a high priority (1.0), ensuring that it always take preference over e.g. music (by assigning a music playing node a priority of 0.8). The volume is controlled by `min_vol` and `max_vol`, being floats between 0.0 (muted) and 1.0 (max volume). The player sets the volume to `min_vol` when another player with higher priority starts playing and sets it back to `max_vol` when that other component stops. Furthermore, the class wraps the strange pygame event handling into an event-driven framework, where programmers can register a `stop_callback` to be called whenever the playing ends. Also, optionally, `play` methods can be used _blocking_ to wait for a tune to finish playing.

This should IMO be used by @nilsbore and @cdondrup for their components, and so I seek their opinion on this. Tested with three components in parallel and confirmed working nicely (both on OS X and Linux).

### CODE REVIEW

**Comment by cburbridge** [comment]
Did not run it, but the idea is great and the code looks good...

**Comment by nilsbore** [comment]
Agreed, will integrate this with one of my nodes tomorrow for some testing.

**Comment by marc-hanheide** [comment]
thanks, @cburbridge and @nilsbore. @nilsbore let me know if it works and then I shall merge it.

**Comment by marc-hanheide** [comment]
Actually, on a second thought it was a stupid idea to put this in the strands_ui package. I'll move it into a new one, as clearly this will soon cause problems, when `mary_tts` depends on `strands_ui`, which - as a kind of meta-package that it still is - depends on `mary_tts` etc... So, please wait with testing until I did the move.

**Comment by marc-hanheide** [comment]
OK, the move is complete. The new stuff is now in a new package `pygame_managed_player`, if you want to give it a go.

**Comment by marc-hanheide** [comment]
any success yet, @nilsbore ?

**Comment by nilsbore** [comment]
Tested with https://github.com/strands-project/strands_deployment/pull/80 . Seems to work fine. Still have to test multiple players though.

**Comment by nilsbore** [comment]
But I can just use the test code for that, 1s.

**Comment by nilsbore** [comment]
Hmm, I just get a weird cursor (looks like a cross) when I try to use run the `pygame_player.py` with a song and priority(?) as the arguments, no music playing and no output. Do I need to do something more? Tried both running directly in folder and with rosrun (e.g. `rosrun pygame_managed_player pygame_player.py /home/nbore/Music/The_xx-Coexist/02-the_xx-chained.mp3 0.8`).

**Comment by marc-hanheide** [comment]
That is strange.... I can't look into it right now. But the call looks correct, so something must be buggy...

**Comment by nilsbore** [comment]
@marc-hanheide The problem for me seems to be a missing `#!/usr/bin/env python` at the top of the file, works with it in place.

**Comment by nilsbore** [comment]
So how does it work if a node gets killed while it's playing? For me the volume of the node with lower priority is not reset after I kill the one with higher priority. Maybe they should emit their priority and signal that they are playing once in a while to enable this?

**Comment by marc-hanheide** [comment]
not easily done... I was thinking of registering a shutdown callback (see http://wiki.ros.org/rospy/Overview/Initialization%20and%20Shutdown#Registering_shutdown_hooks) but there messages are not guaranteed to be published. What you are suggesting is to have some watchdog, where each component publishes when it has last updated and then drop it off the priority map when not updated for a long time? This would be possible, but not really elegant, would it? I mean, is this an actual problem in the use cases we look at?

**Comment by marc-hanheide** [comment]
ok, added the python header

**Comment by marc-hanheide** [comment]
I think I want to postpone your suggestion and turn it into an improvement issue, rather than holding back merging this much longer.

**Comment by nilsbore** [comment]
Yeah, it would probably add a lot of overhead. And yes, I can't think of a scenario like this of the top of my head. If e.g. the recovery behaviour is preempted we can pause the music before returning.

**Comment by nilsbore** [comment]
So I'm happy to have this merged.

**Comment by marc-hanheide** [comment]
merged and also released as updated debian package

**Pull request merged**
