### PR TITLE
changes to deal with new launch and repo structure

### LINKED ISSUE #28: [nav_help_speech] starting mary?
I was completely unaware that this package launches mary. I think mary should be launched by one of the more general launch files because it is not only used during the navigation.

### PR DESCRIPTION
**Pull request by bfalacerda**
closes https://github.com/strands-project/strands_ui/issues/28

### CODE REVIEW

**Comment by bfalacerda** [comment]
needs:

 https://github.com/strands-project/strands_ui/pull/43
https://github.com/strands-project/strands_navigation/pull/90
https://github.com/strands-project/strands_recovery_behaviours/pull/3

**Comment by bfalacerda** [comment]
I just noticed that with this changes strands_ui now depends of strands_recovery_behaviours which doesn't make sense. I think it's better to just move these help packages to strands_recovery_behaviours and have it depending on strands_ui instead.

**Comment by marc-hanheide** [comment]
yes it really does! Will you take care of this?

**Comment by bfalacerda** [comment]
yess

**Comment by cdondrup** [comment]
@BFALacerda how are the changes coming? Should I merge this in the mean time?
Just asking because strands_hri depends on this repo now.

**Comment by bfalacerda** [comment]
Let me move the packages to strands_recovery_behaviours then, and add it to this PR. That should delete the stupid dependencies. 5 min

**Comment by cdondrup** [comment]
Sounds great. Thanks!

**Comment by bfalacerda** [comment]
done

**Comment by cdondrup** [comment]
Thank you. This just failed because in my metapackage I have the `nav_help_s*` packages as run dependencies. Will fix.

**Pull request merged**
